---
title: "graphics with ggplot2"
author: "Helen Fredricks"
date: "October 22, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Learning ggplot2


```{r}
# install and load tidyverse
#install.packages("tidyverse")
#library(tidyverse)
install.packages("ggplot2")
install.packages("readr")
library(ggplot2)
library(readr)


#National Parks in California
ca <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/ca.csv") 

#Acadia National Park
acadia <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/acadia.csv")

#Southeast US National Parks
se <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/se.csv")

#2016 Visitation for all Pacific West National Parks
visit_16 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/visit_16.csv")

#All Nationally designated sites in Massachusetts
mass <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/mass.csv")



```
```{r}
ggplot(data = ca) +
    geom_point(aes(x = year, y = visitors, color = park_name)) +
    labs(x = "Year",
       y = "Visitation",
       title = "California National Park Visitation") +
    theme_bw() +
    theme(legend.title=element_blank())
```
```{r}
ggplot(data = se) +
    geom_point(aes(x = year, y = visitors, color = state)) +
    labs(x = "Year",
       y = "# of visitors",
       title = "Southeast Region National Park Visitation") +
    theme_light() +
    theme(legend.title=element_blank(),
          axis.text.x = element_text(angle = 60, size = 20, color = "blue"))

```
```{r}
ggplot(data = se) +
  geom_point(aes(x = year, y = visitors, color = park_name)) +
               facet_wrap( ~ state, scales = "free")
```
```{r}
ggplot(data = se) +
  geom_jitter(aes(x = park_name, y = visitors), alpha = 0.4, width = 0.1)


```
```{r}
ggplot(se) + geom_line(aes(x = year, y = visitors, color = park_name))+
  theme_bw()
  

```
```{r}
ggplot(acadia, aes(x = year, y = visitors)) +
  geom_point() +
  geom_line() +
  geom_smooth() +
  coord_flip() +
  theme(legend.position = "none") 


```
```{r}
myplot <- ggplot(visit_16, aes(x = state, y = visitors, fill = park_name)) +
  geom_bar(stat = "identity", position = "dodge")

myplot

ggsave(filename = "myplot.png", myplot)

#geom_bar is already running stats, its giving you a count statistic, you can tell it to do something else
```

